### ISSUE TITLE
是否不支持不同类型数组的嵌套定义？

### ISSUE THREAD

**Issue by hzj730** [sy-yanghuan/proton#13]
格式定义：` {int Id;string[] Names}[]`
值： `10001;aa,bb,10002;cc,dd,10003;ee,ff`

Error信息：
`ValueError: ("could not convert string to float: 'bb'", '英雄|Hero has a error in 5 row 9(Test) column in hero.xlsx', '')`

` {int Id;int[] Names}[]` 同类型定义不会报错

**Comment by yanghuan** [comment]
都不可以的， 目前解析器是一个非常简单的结构，对数组直接使用 逗号 Split , 对数组的嵌套分割会有问题

**Comment by hzj730** [comment]
> 都不可以的， 目前解析器是一个非常简单的结构，对数组直接使用 逗号 Split , 对数组的嵌套分割会有问题

了解
